const LANG = {
  tr: {
    'lang.name': 'Türkçe',
    'lang.flag': 'TR',
    'page.title': 'Vertex Konsol',
    'page.desc': 'Vertex içerikleri, kullanıcı yönetimi ve sistem yönetimi için merkezi kontrol paneli.',
    'loader.text': 'Vertex Konsol Başlatılıyor',
    'login.title': 'VERTEX KONSOL',
    'login.subtitle': 'Sistem Yönetim Modülü',
    'login.email': 'E-posta Adresiniz',
    'login.password': 'Şifreniz',
    'login.btn': 'Oturum Aç',
    'login.or': 'veya',
    'header.brand': 'VERTEX',
    'header.system': 'Sistem Portal',
    'header.theme': 'Temayı Değiştir',
    'header.logout': 'Çıkış',
    'nav.contributors': 'Katılımcı',
    'nav.models': 'Modeller',
    'nav.news': 'Haberler',
    'nav.notifications': 'Bildirim',
    'nav.system': 'Sistem',
    'nav.profile': 'Profil',
    'contributors.title': 'Katılımcı Yönetimi & Yetkiler',
    'contributors.desc': 'Vertex topluluk üyelerini inceleyin, onaylayın ve yönetici yetkilerini yönetin.',
    'contributors.section': 'Başvuran Adaylar',
    'contributors.refresh': 'Yenile',
    'contributors.filter.all': 'Tümü',
    'contributors.filter.verified': 'Onaylılar',
    'contributors.filter.unverified': 'Onay Bekleyenler',
    'contributors.filter.age14': '14-15 Yaş',
    'contributors.filter.age16': '16-17 Yaş',
    'contributors.filter.age18': '18+ Yaş',
    'contributors.filter.linkedin': 'LinkedIn',
    'contributors.filter.github': 'GitHub',
    'contributors.filter.interview': 'Mülakatlılar',
    'contributors.interview_date': 'Mülakat Tarihi',
    'contributors.no_interview': 'Belirtilmedi',
    'contributors.search': 'Listede isim, e-posta veya biyografi ara...',
    'contributors.load_hint': 'Listeyi yüklemek için Yenile butonuna basın.',
    'contributors.loading': 'Yükleniyor...',
    'contributors.load_error': 'Katılımcılar yüklenemedi.',
    'contributors.empty': 'Katılımcı bulunamadı.',
    'contributors.no_match': 'Kriterlere uyan başvuru bulunamadı.',
    'contributors.search_no_match': 'Arama sonucuna uygun katılımcı bulunamadı.',
    'contributors.delete_confirm': 'Emin misiniz? Başvuru tamamen silinecek.',
    'contributors.deleted': 'Katılımcı başarıyla silindi.',
    'contributors.verified_label': 'Doğrulandı',
    'contributors.unverified_label': 'Doğrulanmadı',
    'contributors.verify_updated': 'Doğrulama durumu güncellendi!',
    'admin.title': 'Yönetici Rolü Tanımla',
    'admin.desc': 'Doğrulanmış bir Vertex üyesinin e-posta adresini girerek yönetici kontrol yetkisi tanımlayın.',
    'admin.email_label': 'Kullanıcı E-postası',
    'admin.email_placeholder': 'kullanici@vertexishere.com',
    'admin.email_hint': 'Kullanıcı sisteme kayıtlı olmalıdır.',
    'admin.grant_btn': 'Yönetici Yetkisi Ver',
    'admin.granting': 'YETKİ VERİLİYOR',
    'admin.grant_success': 'Yönetici rolü başarıyla verildi.',
    'models.title': 'Yapay Zeka Modelleri',
    'models.desc': 'Uygulamada yayında olan çevrimdışı (On-Device) ve rol yapma yapay zeka modellerini yönetin.',
    'models.form_title': 'Model Ekleme ve Düzenleme',
    'models.classification': 'Model Sınıflandırması',
    'models.roleplay': 'Rol Yapma',
    'models.offline': 'Çevrimdışı',
    'models.producer': 'Geliştirici Firma',
    'models.producer_ph': 'Ör. Google, Meta',
    'models.id': 'Model Kimliği (ID)',
    'models.id_ph': 'Ör. gemma-2b-it',
    'models.card_info': 'Arayüz Kart Bilgileri (İngilizce)',
    'models.title_field': 'Model Adı (Title)',
    'models.title_ph': 'Görüntülenecek başlık',
    'models.summary': 'Özet (Summary)',
    'models.summary_ph': 'Karttaki kısa özet açıklaması',
    'models.description': 'Tam Detaylı Açıklama (Description)',
    'models.description_ph': 'Model yetenekleri hakkında detaylı metin',
    'models.roleplay_config': 'Rol Yapma Konfigürasyonu',
    'models.system_prompt': 'Sistem Promptu (System Role)',
    'models.system_prompt_ph': 'Karakterin uyacağı yönerge promptu',
    'models.offline_config': 'Çevrimdışı Bağlantılar & Donanım',
    'models.gguf_url': 'GGUF HuggingFace İndirme Adresi',
    'models.gguf_ph': 'https://huggingface.co/.../*.gguf',
    'models.file_size': 'Dosya Boyutu (MB)',
    'models.file_size_ph': 'MB cinsinden',
    'models.ram': 'Gereken RAM (MB)',
    'models.ram_ph': 'MB cinsinden',
    'models.io_types': 'Girdi ve Çıktı Tipleri',
    'models.input_types': 'Girdi Tipleri',
    'models.output_types': 'Çıktı Tipleri',
    'models.image': 'Görsel',
    'models.video': 'Video',
    'models.audio': 'Ses',
    'models.file': 'Dosya',
    'models.text': 'Metin',
    'models.license_section': 'Lisans & Kaynak',
    'models.creator': 'Geliştirici',
    'models.license_type': 'Lisans Türü',
    'models.license_type_ph': 'Lisans ismi',
    'models.source': 'Kaynak',
    'models.license_url': 'Lisans Linki',
    'models.license_url_ph': 'Lisans URL adresi',
    'models.template_section': 'Şablon Kuralları (Prompter)',
    'models.template_select': 'Hazır Şablon Formatı',
    'models.template_none': '-- Şablon Seçilmedi --',
    'models.token_system_start': 'Sistem Başlangıç',
    'models.token_system_end': 'Sistem Bitiş',
    'models.token_user_start': 'Kullanıcı Başlangıç',
    'models.token_user_end': 'Kullanıcı Bitiş',
    'models.token_assistant_start': 'Asistan Başlangıç',
    'models.token_assistant_end': 'Asistan Bitiş',
    'models.token_stop': 'Durdurma Belirteçleri',
    'models.token_stop_ph': '<|im_end|>, </s>',
    'models.token_ignore': 'Yok Sayılacak Regex',
    'models.token_ignore_ph': '^[Düşünme Adımları]...$',
    'models.image_section': 'Resim Dosyası',
    'models.image_label': 'Model Temsili Resmi',
    'models.save_btn': 'Değişiklikleri Kaydet',
    'models.cancel_btn': 'İptal Et',
    'models.active_models': 'Aktif Modeller',
    'models.offline_count': 'Çevrimdışı:',
    'models.roleplay_count': 'Rol Yapma:',
    'models.no_models': 'Kayıtlı model bulunamadı.',
    'models.all_models': 'Tüm Modeller Ağacı',
    'models.loading': 'Yükleniyor...',
    'news.title': 'Haberler & Duyurular',
    'news.desc': 'Mobil uygulama ana sayfasındaki haber akışında görünecek makaleleri yayınlayın.',
    'news.form_title': 'Haber Duyurusu Yaz',
    'news.tr_section': 'Türkçe Yayın İçeriği',
    'news.tr_title': 'Başlık (TR)',
    'news.tr_title_ph': 'Haber başlığı',
    'news.tr_summary': 'Özet (TR)',
    'news.tr_summary_ph': 'Haber akış kartındaki özet',
    'news.tr_content': 'Detay (TR)',
    'news.tr_content_ph': 'Makale detaylı içeriği (Markdown destekler)',
    'news.tr_cover': 'Kapak Fotoğrafı (TR)',
    'news.en_section': 'English Content (İngilizce)',
    'news.en_title': 'Title (EN)',
    'news.en_title_ph': 'Article Title',
    'news.en_summary': 'Summary (EN)',
    'news.en_summary_ph': 'Short description summary',
    'news.en_content': 'Body (EN)',
    'news.en_content_ph': 'Detailed content details',
    'news.en_cover': 'Cover Image (EN)',
    'news.meta_section': 'Meta Veri & Referanslar',
    'news.tags': 'Etiketler',
    'news.tags_ph': 'Ör. guncelleme, topluluk (virgülle ayırın)',
    'news.references': 'Kaynak Bağlantıları (URL)',
    'news.references_ph': 'Her satıra bir adet bağlantı gelecek şekilde',
    'news.publish_btn': 'Haber Makalesini Yayınla',
    'news.active_articles': 'Aktif Yayındaki Haberler',
    'news.no_articles': 'Yayınlanmış haber makalesi bulunamadı.',
    'notif.title': 'Anlık Bildirimler',
    'notif.desc': 'Vertex kullanıcılarına hedeflenmiş veya zamanlanmış anlık push bildirimleri gönderin.',
    'notif.form_title': 'Push Bildirim Gönder / Ayarla',
    'notif.template_section': 'Hazır Şablon & Anahtarlar',
    'notif.template_label': 'Hazır Şablonlar',
    'notif.template_none': '-- Şablon Kullanma --',
    'notif.title_key': 'Başlık Anahtarı (Title Key)',
    'notif.title_key_ph': 'Ör. notificationTitleKey',
    'notif.body_key': 'Gövde Anahtarı (Body Key)',
    'notif.body_key_ph': 'Ör. notificationBodyKey',
    'notif.data_payload': 'İsteğe Bağlı Veri Yükü (JSON)',
    'notif.data_payload_ph': '{"modelId": "llama-8b"}',
    'notif.fallback_section': 'Yedek Bildirim İçeriği',
    'notif.fallback_title': 'Genel Başlık',
    'notif.fallback_title_ph': 'Yedek bildirim başlığı',
    'notif.fallback_body': 'Genel Mesaj Gövdesi',
    'notif.fallback_body_ph': 'Gönderilecek genel mesaj metni',
    'notif.targeting': 'Kullanıcı Hedefleme',
    'notif.target_label': 'Alıcı Grubu',
    'notif.target_placeholder': 'Bir grup seçin...',
    'notif.target_all': 'Tüm Kullanıcılar',
    'notif.target_single': 'Tek Bir Kullanıcı (UID ile)',
    'notif.target_level': 'Abonelik Seviyesine Göre',
    'notif.uid_label': 'Kullanıcı UID',
    'notif.uid_ph': 'Firebase UID adresi',
    'notif.level_label': 'Minimum Abonelik Düzeyi',
    'notif.level0': 'Ücretsiz Üyeler (Level 0)',
    'notif.level1': 'Plus Üyeler (Level 1)',
    'notif.level2': 'Pro Üyeler (Level 2)',
    'notif.level3': 'Ultra Üyeler (Level 3)',
    'notif.mode': 'Gönderim Modu',
    'notif.send_now': 'Hemen Gönder',
    'notif.schedule': 'Zamanla',
    'notif.datetime': 'Tarih ve Saat',
    'notif.submit_btn': 'Bildirimi Gönder',
    'notif.scheduled_title': 'Zamanlanmış Bildirimler',
    'notif.no_scheduled': 'Kuyrukta bekleyen bildirim bulunamadı.',
    'system.title': 'Sunucu & Sistem Ayarları',
    'system.desc': 'Sistem altyapısını kontrol edin, bakım modunu açıp kapatın veya atıflar sayfasını yayınlayın.',
    'system.maintenance': 'Sunucu Bakım Modu',
    'system.maintenance_desc': 'Sunucu bakım modunu açmak yeni giriş işlemlerini durdurur. Giriş yapmış kullanıcılar yerel modda devam edebilir.',
    'system.checking': 'Durum Kontrol Ediliyor...',
    'system.loading_btn': 'Yükleniyor...',
    'system.live': 'Canlı',
    'system.maintenance_on': 'BAKIM',
    'system.enable_maint': 'Bakım Modunu Aç',
    'system.disable_maint': 'Bakım Modunu Kapat',
    'system.saving': 'KAYDEDİLİYOR',
    'system.retry': 'Tekrar Dene',
    'system.maint_updated': 'Bakım modu başarıyla güncellendi.',
    'system.attributions': 'Atıflar Sayfasını Yayınla',
    'system.attributions_desc': 'Model veya lisans güncellemelerinin ardından atıflar sayfasını tekrar derleyip yayınlamak için bu tetikleyiciyi kullanın.',
    'system.attributions_synced': 'Durum: Güncel',
    'system.attributions_pending': 'Durum: Güncelleme Gerekli',
    'system.attributions_btn': 'Atıf Sayfasını Güncelle',
    'system.attributions_publish': 'Değişiklikleri Yayınla',
    'system.attributions_uptodate': 'Güncel',
    'system.attributions_trigger': 'TETİKLENİYOR...',
    'system.attributions_retry': 'Tekrar Dene',
    'system.export': 'Verileri Dışa Aktar / İndir',
    'system.export_desc': 'Sistemde yüklü olan katılımcı listelerini, AI modellerini veya haber makalelerini seçtiğiniz formatta yerel olarak bilgisayarınıza indirebilirsiniz.',
    'system.export_type': 'Dışa Aktarılacak Veri',
    'system.export_contributors': 'Katılımcı Başvuruları',
    'system.export_manual_models': 'Eklenen AI Modelleri (Küratörlü)',
    'system.export_all_models': 'Tüm Modeller Veritabanı',
    'system.export_articles': 'Yayınlanan Haberler',
    'system.export_format': 'Dosya Formatı',
    'system.export_json': 'JSON Formatı (.json)',
    'system.export_csv': 'CSV Formatı (Excel uyumlu .csv)',
    'system.export_btn': 'Veriyi Derle ve İndir',
    'system.export_no_data': 'Seçtiğiniz veriler henüz yüklenmemiş. Lütfen önce ilgili sekmesini ziyaret edip verilerin gelmesini bekleyin.',
    'system.export_no_rows': 'Dışa aktarılacak satır bulunamadı.',
    'system.export_success': 'Veriler başarıyla dışa aktarıldı.',
    'system.export_downloaded': 'Dosya başarıyla indirildi!',
    'system.gcs_backup': 'Google Cloud Storage (GCS) Yedekleme',
    'system.gcs_desc': 'Otomatik GCS organizasyon yedekleme mekanizması (GitHub Actions üzerinden) şu anda <strong style="color: var(--accent-sage);">AKTİF</strong> ve çalışır durumda.',
    'system.verify_user': 'Katılımcı Doğrula (Manuel)',
    'system.verify_desc': 'Bir kullanıcının e-posta adresini (E-posta veya UID girerek) anında doğrulanmış durumuna getirin.',
    'system.verify_id': 'Kullanıcı UID veya E-posta',
    'system.verify_btn': 'Doğrula',
    'system.verify_success': 'Kullanıcı e-postası başarıyla doğrulandı.',
    'system.remove_admin': 'Yönetici Yetkisi Al',
    'system.remove_admin_desc': 'Bir sistem yöneticisinin (Admin) yetkilerini e-posta adresi üzerinden iptal edin.',
    'system.remove_email': 'E-posta Adresi',
    'system.remove_btn': 'Yetkiyi İptal Et',
    'system.remove_success': 'Yönetici yetkisi başarıyla iptal edildi.',
    'system.admin_list': 'Aktif Sistem Yöneticileri',
    'system.loading_admins': 'Yükleniyor...',
    'system.error': 'Hata',
    'dept.title': 'Departman Erişim Yetkileri',
    'dept.desc': 'Her departmanın hangi yönetim sekmelerine erişebileceğini belirleyin. Değişiklikler otomatik kaydedilir.',
    'dept.loading': 'Yükleniyor...',
    'dept.saved': 'Departman yetkileri kaydedildi.',
    'dept.assign_title': 'Kullanıcıya Departman Ata',
    'dept.assign_desc': 'Kullanıcının erişeceği departmanları seçin. Kaydetme mevcut departman listesinin yerini alır.',
    'dept.assign_email': 'Kullanıcı E-postası',
    'dept.assign_dept': 'Departmanlar',
    'dept.select_hint': 'En az bir departman seçin.',
    'dept.users_title': 'Departman Kullanıcıları',
    'dept.refresh': 'Yenile',
    'dept.search': 'İsim, e-posta veya departman ara...',
    'dept.empty': 'Departman atanmış kullanıcı bulunamadı.',
    'dept.no_match': 'Aramayla eşleşen kullanıcı bulunamadı.',
    'dept.load_error': 'Kullanıcı listesi yüklenemedi. Sunucu fonksiyonunu kontrol edin.',
    'dept.backend_required': 'Çoklu departman için sunucu fonksiyonu henüz yayınlanmadı.',
    'dept.edit': 'Düzenle',
    'dept.select_dept': 'Departman seçin...',
    'dept.assign_btn': 'Departman Ata',
    'dept.assign_success': 'Departman başarıyla atandı.',
    'dept.group_ust': 'Üst Departmanlar',
    'dept.group_orta': 'Orta Departmanlar',
    'dept.group_alt': 'Alt Departmanlar',
    'dept.essence': 'Essence',
    'dept.core': 'Core',
    'dept.senatus': 'Senatus',
    'dept.pulse': 'Pulse',
    'dept.chroma': 'Chroma',
    'dept.catalyst': 'Catalyst',
    'dept.envoy': 'Envoy',
    'dept.aero': 'Aero',
    'dept.array': 'Array',
    'dept.scout': 'Scout',
    'dept.vertest': 'Vertest',
    'dept.tensor': 'Tensor',
    'dept.curia': 'Curia',
    'panel.contributors.list': 'Başvuran Adaylar',
    'panel.system.adminRole': 'Yönetici Rolü Tanımla',
    'panel.contributors.vertexStatus': 'Vertex Durumu Değiştir',
    'panel.models.manage': 'Model Ekleme ve Düzenleme',
    'panel.models.library': 'Aktif Modeller & Ağaç',
    'panel.news.editor': 'Haber Duyurusu Yaz',
    'panel.news.published': 'Aktif Yayındaki Haberler',
    'panel.notifications.sender': 'Push Bildirim Gönder',
    'panel.notifications.scheduled': 'Zamanlanmış Bildirimler',
    'panel.subscriptions.assign': 'Kullanıcıya Abonelik Tanımla',
    'panel.subscriptions.list': 'Tanımlı Abonelikler',
    'panel.system.deptPerms': 'Departman Erişim Yetkileri',
    'panel.system.deptAssign': 'Kullanıcıya Departman Ata',
    'panel.system.deptUsers': 'Departman Kullanıcıları',
    'panel.system.manualVerify': 'Katılımcı Doğrula (Manuel)',
    'panel.system.removeAdmin': 'Yönetici Yetkisi Al',
    'panel.system.adminList': 'Aktif Sistem Yöneticileri',
    'panel.system.serverStatus': 'Sunucu Bakım Modu',
    'panel.system.attributions': 'Atıflar Sayfasını Yayınla',
    'panel.system.exporter': 'Verileri Dışa Aktar',
    'perms.dept_col': 'Departman',
    'perms.panel_menu': 'Panel ayarları',
    'perms.drag_hint': 'Paneli taşı (sürükle-bırak)',
    'perms.resize_hint': 'Yeniden boyutlandır',
    'perms.order_reset': 'Panel düzenini sıfırla',
    'perms.menu_access': 'Erişim (rank bazlı)',
    'perms.menu_content': 'İçerik ayarları',
    'perms.menu_chips': 'Filtre kategorileri',
    'perms.desc': 'Her departmanın hangi bölümleri göreceğini ve düzenleyebileceğini belirleyin. Hücreler Yok / Gör / Düzenle arasında geçer; kanal ikonuyla panelleri tek tek ayarlayabilirsiniz. Değişiklikler otomatik kaydedilir.',
    'perms.cycle_hint': 'Yok → Gör → Düzenle arasında geçer',
    'perms.level_none': 'Yok',
    'perms.level_read': 'Gör',
    'perms.level_write': 'Düzenle',
    'perms.preset_none': 'Tüm kanalları kapat',
    'perms.preset_read': 'Tüm kanalları görüntüleme (read-only) aç',
    'perms.preset_write': 'Tüm kanallara tam yetki ver',
    'perms.detail_btn': 'Kanalın panellerini tek tek ayarla',
    'perms.detail_title': 'Kanal Yetkileri',
    'perms.detail_hint': 'Bu kanalın alt panelleri için özel seviye belirleyin. Ok işaretsiz hücreler genel (matrix) seviyesinden miras alır; ↺ ile genel seviyeye döner.',
    'perms.save_hint': 'Sunucudaki saveDepartmentPermissions fonksiyonu eski. adminsite-main/server/department-functions.cjs dosyasini functions projenize kopyalayip deploy edin.',
    'perms.override_hint': 'Bu kanalda panel bazılı özel ayar var — ayrıntı için kanal ikonuna bas',
    'perms.hidden_title': 'Gizlenecek Alan Grupları',
    'perms.hidden_hint': 'İşaretli alan grupları bu departman için sunucuda maskelenir — tarayıcıya hiç gönderilmez. Yalnızca Katılımcı kanalı için geçerlidir.',
    'perms.hidden_contact': 'Kişisel bilgiler (e-posta, telefon)',
    'perms.hidden_age': 'Yaş',
    'perms.hidden_links': 'Sosyal bağlantılar',
    'perms.hidden_interview': 'Mülakat bilgileri',
    'perms.inherit_label': 'Genel seviyeden miras',
    'perms.reset_btn': 'Genel seviyeye dön',
    'contributors.edit_title': 'Başvuruyu Düzenle',
    'contributors.save_btn': 'Değişiklikleri Kaydet',
    'contributors.cancel_btn': 'İptal',
    'contributors.edit_updated': 'Başvuru güncellendi.',
    'contributors.field_name': 'Ad Soyad',
    'contributors.field_email': 'E-posta',
    'contributors.field_phone': 'Telefon',
    'contributors.field_age': 'Yaş',
    'contributors.field_department': 'Departman',
    'contributors.field_language': 'Dil',
    'contributors.field_linkedin': 'LinkedIn',
    'contributors.field_github': 'GitHub',
    'contributors.field_interview': 'Mülakat Tarihi',
    'contributors.field_about': 'Hakkında',
    'contributors.field_interview_details': 'Mülakat Detayları',
    'nav.chat': 'Sohbet',
    'chat.title': 'Sohbet',
    'chat.desc': 'Departman kanalları, görev takibi ve @etiket bildirimleri.',
    'chat.channels': 'Kanallar',
    'chat.no_channels': 'Henüz kanal yok.',
    'toast.dismiss_hint': 'Bildirimi kapatmak için tıkla',
    'chat.login_hint': 'Kanalları görmek için oturum açın.',
    'chat.loading': 'Yükleniyor...',
    'chat.empty': 'Bu kanalda henüz mesaj yok.',
    'chat.select_hint': 'Bir kanal seçin.',
    'chat.readonly': 'Bu kanalda yalnızca yöneticiler yazabilir.',
    'chat.open_all': 'Tüm departmanlara açık',
    'chat.placeholder': 'Mesaj yazın — @Departman veya @mail ile etiketleyin',
    'chat.as_task': 'Görev/Sorun',
    'chat.task_open': 'Açık',
    'chat.task_done': 'Çözüldü',
    'chat.task_done_btn': 'Çözüldü işaretle',
    'chat.task_reopen': 'Yeniden aç',
    'chat.form_create': 'Kanal Oluştur',
    'chat.form_edit': 'Kanalı Düzenle',
    'chat.name_required': 'Kanal adı gerekli.',
    'chat.created': 'Kanal oluşturuldu.',
    'chat.updated': 'Kanal güncellendi.',
    'user_menu.admin': 'Yönetici',
    'user_menu.profile': 'Profil',
    'user_menu.theme': 'Temayı Değiştir',
    'nav.subscriptions': 'Abonelik',
    'subs.title': 'Abonelik Yönetimi',
    'subs.desc': 'Kullanıcı hesaplarına manuel Plus, Pro veya Ultra abonelik tanımlayın, aktif atamaları takip edin.',
    'subs.form_title': 'Kullanıcıya Abonelik Tanımla',
    'subs.form_desc': 'Kullanıcının hesap e-postasını girerek seçtiğiniz aboneliği anında otomatik olarak atayın; süre en fazla 1 yıl olabilir.',
    'subs.username_label': 'Kullanıcı İsmi',
    'subs.username_ph': 'Uygulamadaki kullanıcı adı',
    'subs.username_hint': 'Listede görüntülemek için; atama e-posta ile eşleştirilir.',
    'subs.email_label': 'Hesap Gmaili (E-posta)',
    'subs.email_hint': 'Kullanıcı sisteme bu e-posta ile kayıtlı olmalıdır.',
    'subs.plan_label': 'Abonelik Seviyesi',
    'subs.plan_plus': 'Plus Üyelik',
    'subs.plan_pro': 'Pro Üyelik',
    'subs.plan_ultra': 'Ultra Üyelik',
    'subs.end_label': 'Bitiş Zamanı (En Fazla 1 Yıl)',
    'subs.end_label_short': 'Bitiş',
    'subs.duration_hint': 'Abonelik anında başlar; en fazla 1 yıl ileri tarih ayarlanabilir.',
    'subs.assign_btn': 'Aboneliği Tanımla',
    'subs.assigning': 'ATANIYOR',
    'subs.assign_success': 'Abonelik başarıyla tanımlandı.',
    'subs.expires_past': 'Bitiş zamanı gelecekte bir tarih olmalıdır.',
    'subs.max_one_year': 'Abonelik süresi en fazla 1 yıl olabilir.',
    'subs.list_title': 'Tanımlı Abonelikler',
    'subs.refresh': 'Yenile',
    'subs.search': 'İsim, e-posta veya seviye ara...',
    'subs.load_hint': 'Listeyi yüklemek için Yenile butonuna basın.',
    'subs.list_loading': 'Abonelikler yükleniyor...',
    'subs.empty': 'Tanımlı abonelik bulunamadı.',
    'subs.no_match': 'Aramayla eşleşen abonelik bulunamadı.',
    'subs.load_error': 'Abonelik listesi yüklenemedi. Sunucu fonksiyonunu kontrol edin.',
    'subs.remove_btn': 'Kaldır',
    'subs.remove_confirm': 'Bu kullanıcının aboneliğini kaldırmak istediğinize emin misiniz?',
    'subs.removing': 'KALDIRILIYOR',
    'subs.remove_success': 'Abonelik başarıyla kaldırıldı.',
    'subs.badge_active': 'Aktif',
    'subs.badge_expired': 'Süresi Doldu',
    'subs.bulk_toggle': 'Toplu Tanımlama',
    'subs.bulk_hint': 'Posta listesini yapıştır: virgül, noktalı virgül, boşluk veya alt alta ayırabilirsin — ayırma işini sunucu yapar ve listeyi 50\'lik gruplara bölerek aralıklarla tanımlar. Abonelik seviyesi ve bitiş zamanı yukarıdaki alanlardan alınır.',
    'subs.bulk_label': 'Posta Listesi',
    'subs.bulk_placeholder': 'posta1@gmail.com, posta2@gmail.com, posta3@gmail.com ...',
    'subs.bulk_btn': 'Toplu Tanımla',
    'subs.bulk_running': 'TOPLU ATAMA SÜRÜYOR...',
    'subs.bulk_started': 'Toplu tanımlama başladı; e-posta sayısına göre birkaç dakika sürebilir.',
    'subs.bulk_granted': 'hesaba tanımlandı',
    'subs.bulk_failed': 'hatalı',
    'subs.bulk_failed_title': 'Tanımlanamayan adresler',
    'subs.bulk_invalid_title': 'Geçersiz girdiler',
    'profile.title': 'Profilim',
    'profile.desc': 'Hesap bilgilerinizi ve panel erişiminizi görüntüleyin.',
    'profile.display_name': 'Görünen ad',
    'profile.save': 'Profili Kaydet',
    'profile.saved': 'Profil kaydedildi.',
    'profile.access': 'Erişim Bilgileri',
    'profile.role': 'Rol',
    'profile.departments': 'Departmanlar',
    'profile.uid': 'Kullanıcı kimliği',
    'profile.admin': 'Yönetici',
    'profile.member': 'Departman üyesi',
    'profile.none': 'Atanmadı',
    'profile.menu_btn': 'Menü',
    'profile.uid_copied': 'Kimlik panoya kopyalandı.',
    'profile.uid_copied_fail': 'Kopyalama başarısız.',
    'profile.menu_soon': 'Bu seçenek yakında aktifleşecek.',
    'profile.menu_1': 'Hesap Ayarları',
    'profile.menu_2': 'Bildirim Tercihleri',
    'profile.menu_3': 'Güvenlik',
    'profile.menu_4': 'Oturum Geçmişi',
    'profile.menu_5': 'Tema ve Görünüm',
    'profile.menu_6': 'Dil Tercihleri',
    'profile.menu_7': 'Yardım ve Destek',
    'profile.menu_8': 'Çıkış Yap',
    'profile.perms_title': 'Yetki Özeti',
    'auth.not_admin': 'Bu panele erişim yetkiniz bulunmamaktadır.',
    'auth.login_failed': 'Giriş başarısız:',
    'auth.enter_credentials': 'Lütfen e-posta ve şifrenizi girin.',
    'auth.session_expired': 'Oturum süreniz doldu. Lütfen tekrar giriş yapın.',
    'auth.try_again': 'Tekrar Dene',
    'template.group.system': 'Sistem & Teklifler',
    'template.group.engagement': 'Kullanıcı Etkileşimi',
    'template.group.fun': 'Eğlenceli & Şakalar',
    'template.group.tech': 'Teknik Detaylar',
    'template.group.special': 'Özel Günler',
    'template.newModel': 'Yeni Model Eklendi',
    'template.newFeature': 'Yeni Özellik Eklendi',
    'template.upsellFeature': 'Abonelik Kampanyası',
    'template.appUpdate': 'Uygulama Güncelleme Uyarısı',
    'template.rateApp': 'Uygulamayı Puanla',
    'template.referral': 'Arkadaşına Öner',
    'template.socialMedia': 'Sosyal Medya Katılımı',
    'template.comeback': 'Geri Dönüş Çağrısı (Genel)',
    'template.longTimeNoSee': 'Uzun Süre Giriş Yapmayanlar',
    'template.howAreYou': 'Hal Hatır Sorma',
    'template.goodMorning': 'Günaydın Mesajı',
    'template.goodNight': 'İyi Geceler Mesajı',
    'template.randomFact': 'İlginç Bilgi',
    'template.showerThought': 'Duş Düşünceleri',
    'template.fortuneCookie': 'Şans Kurabiyesi',
    'template.hackerJoke': 'Yazılımcı Şakaları',
    'template.pirate': 'Korsan Modu',
    'template.trollAnime': 'Troll (Anime)',
    'template.trollAiRebellion': 'Troll (Yapay Zeka İsyanı)',
    'template.singularity': 'Singularity',
    'template.detectiveCase': 'Dedektif Hikayesi',
    'template.originStory': 'Hikaye Başlangıcı',
    'template.rejectionStory': 'Reddedilme Anısı',
    'template.cooking': 'Şefin Tarifi',
    'template.existential': 'Varoluşsal Kriz',
    'template.openSource': 'Açık Kaynak Sevgisi',
    'template.offlineReady': 'Çevrimdışı Çalışma Hazır',
    'template.customModel': 'Kendi Modelini Kur',
    'template.dynamicChat': 'Dinamik Sohbet Odaları',
    'template.ggufSupport': 'GGUF Desteği Aktif',
    'template.themeCustomization': 'Tema Özelleştirme',
    'template.homeworkHelper': 'Ödev Asistanı Tanıtımı',
    'template.lowBattery': 'Düşük Batarya Tasarruf Modu',
    'template.newYear': 'Yılbaşı Tebriği',
    'template.valentinesDay': 'Sevgililer Günü',
    'template.ataturkRemembrance': '10 Kasım Atatürk\'ü Anma',
    'template.mothersDay': 'Anneler Günü',
    'template.fathersDay': 'Babalar Günü',
  },

  en: {
    'lang.name': 'English',
    'lang.flag': 'EN',
    'page.title': 'Vertex Console',
    'page.desc': 'Central control panel for Vertex content, user management and system administration.',
    'loader.text': 'Starting Vertex Console',
    'login.title': 'VERTEX KONSOL',
    'login.subtitle': 'System Administration Module',
    'login.email': 'Your Email Address',
    'login.password': 'Your Password',
    'login.btn': 'Sign In',
    'login.or': 'or',
    'header.brand': 'VERTEX',
    'header.system': 'System Portal',
    'header.theme': 'Toggle Theme',
    'header.logout': 'Logout',
    'nav.contributors': 'Contributors',
    'nav.models': 'Models',
    'nav.news': 'News',
    'nav.notifications': 'Notifications',
    'nav.system': 'System',
    'nav.profile': 'Profile',
    'contributors.title': 'Contributor Management & Permissions',
    'contributors.desc': 'Review Vertex community members, approve them and manage admin permissions.',
    'contributors.section': 'Applicants',
    'contributors.refresh': 'Refresh',
    'contributors.filter.all': 'All',
    'contributors.filter.verified': 'Verified',
    'contributors.filter.unverified': 'Pending',
    'contributors.filter.age14': 'Age 14-15',
    'contributors.filter.age16': 'Age 16-17',
    'contributors.filter.age18': 'Age 18+',
    'contributors.filter.linkedin': 'LinkedIn',
    'contributors.filter.github': 'GitHub',
    'contributors.filter.interview': 'With Interview',
    'contributors.interview_date': 'Interview Date',
    'contributors.no_interview': 'Not Scheduled',
    'contributors.search': 'Search by name, email or bio...',
    'contributors.load_hint': 'Press Refresh to load the list.',
    'contributors.loading': 'Loading contributors...',
    'contributors.load_error': 'Failed to load contributors.',
    'contributors.empty': 'No contributors found.',
    'contributors.no_match': 'No applications match the criteria.',
    'contributors.search_no_match': 'No contributors match your search.',
    'contributors.delete_confirm': 'Are you sure? The application will be permanently deleted.',
    'contributors.deleted': 'Contributor deleted successfully.',
    'contributors.verified_label': 'Verified',
    'contributors.unverified_label': 'Unverified',
    'contributors.verify_updated': 'Verification status updated!',
    'admin.title': 'Assign Admin Role',
    'admin.desc': 'Grant admin control privileges by entering the email of a verified Vertex member.',
    'admin.email_label': 'User Email',
    'admin.email_placeholder': 'user@vertexishere.com',
    'admin.email_hint': 'User must be registered in the system.',
    'admin.grant_btn': 'Grant Admin Role',
    'admin.granting': 'GRANTING',
    'admin.grant_success': 'Admin role granted successfully.',
    'models.title': 'AI Models',
    'models.desc': 'Manage online roleplay and offline (On-Device) AI models published in the app.',
    'models.form_title': 'Add / Edit Model',
    'models.classification': 'Model Classification',
    'models.roleplay': 'Roleplay',
    'models.offline': 'Offline',
    'models.producer': 'Producer',
    'models.producer_ph': 'e.g. Google, Meta',
    'models.id': 'Model ID',
    'models.id_ph': 'e.g. gemma-2b-it',
    'models.card_info': 'Card Details (English)',
    'models.title_field': 'Model Title',
    'models.title_ph': 'Display title',
    'models.summary': 'Summary',
    'models.summary_ph': 'Short card summary',
    'models.description': 'Full Description',
    'models.description_ph': 'Detailed text about model capabilities',
    'models.roleplay_config': 'Roleplay Configuration',
    'models.system_prompt': 'System Prompt (System Role)',
    'models.system_prompt_ph': 'Character instruction prompt',
    'models.offline_config': 'Offline Connections & Hardware',
    'models.gguf_url': 'GGUF HuggingFace Download URL',
    'models.gguf_ph': 'https://huggingface.co/.../*.gguf',
    'models.file_size': 'File Size (MB)',
    'models.file_size_ph': 'In MB',
    'models.ram': 'Required RAM (MB)',
    'models.ram_ph': 'In MB',
    'models.io_types': 'Input & Output Types',
    'models.input_types': 'Input Types',
    'models.output_types': 'Output Types',
    'models.image': 'Image',
    'models.video': 'Video',
    'models.audio': 'Audio',
    'models.file': 'File',
    'models.text': 'Text',
    'models.license_section': 'License & Source',
    'models.creator': 'Creator',
    'models.license_type': 'License Type',
    'models.license_type_ph': 'License name',
    'models.source': 'Source',
    'models.license_url': 'License URL',
    'models.license_url_ph': 'License URL address',
    'models.template_section': 'Template Rules (Prompter)',
    'models.template_select': 'Preset Template Format',
    'models.template_none': '-- No Template --',
    'models.token_system_start': 'System Start',
    'models.token_system_end': 'System End',
    'models.token_user_start': 'User Start',
    'models.token_user_end': 'User End',
    'models.token_assistant_start': 'Assistant Start',
    'models.token_assistant_end': 'Assistant End',
    'models.token_stop': 'Stop Tokens',
    'models.token_stop_ph': '<|im_end|>, </s>',
    'models.token_ignore': 'Ignore Regex',
    'models.token_ignore_ph': '^[Thinking Steps]...$',
    'models.image_section': 'Image File',
    'models.image_label': 'Model Image',
    'models.save_btn': 'Save Changes',
    'models.cancel_btn': 'Cancel',
    'models.active_models': 'Active Models',
    'models.offline_count': 'Offline:',
    'models.roleplay_count': 'Roleplay:',
    'models.no_models': 'No models found.',
    'models.all_models': 'All Models Tree',
    'models.loading': 'Loading...',
    'news.title': 'News & Announcements',
    'news.desc': 'Publish articles that will appear in the news feed on the mobile app home page.',
    'news.form_title': 'Write News Article',
    'news.tr_section': 'Turkish Content',
    'news.tr_title': 'Title (TR)',
    'news.tr_title_ph': 'News title',
    'news.tr_summary': 'Summary (TR)',
    'news.tr_summary_ph': 'News card summary',
    'news.tr_content': 'Content (TR)',
    'news.tr_content_ph': 'Detailed article content (Markdown supported)',
    'news.tr_cover': 'Cover Image (TR)',
    'news.en_section': 'English Content',
    'news.en_title': 'Title (EN)',
    'news.en_title_ph': 'Article Title',
    'news.en_summary': 'Summary (EN)',
    'news.en_summary_ph': 'Short description summary',
    'news.en_content': 'Body (EN)',
    'news.en_content_ph': 'Detailed content details',
    'news.en_cover': 'Cover Image (EN)',
    'news.meta_section': 'Metadata & References',
    'news.tags': 'Tags',
    'news.tags_ph': 'e.g. update, community (comma separated)',
    'news.references': 'Reference Links (URL)',
    'news.references_ph': 'One link per line',
    'news.publish_btn': 'Publish Article',
    'news.active_articles': 'Published Articles',
    'news.no_articles': 'No published articles found.',
    'notif.title': 'Push Notifications',
    'notif.desc': 'Send targeted or scheduled push notifications to Vertex users.',
    'notif.form_title': 'Send / Schedule Notification',
    'notif.template_section': 'Templates & Keys',
    'notif.template_label': 'Template Selection',
    'notif.template_none': '-- No Template --',
    'notif.title_key': 'Title Key',
    'notif.title_key_ph': 'e.g. notificationTitleKey',
    'notif.body_key': 'Body Key',
    'notif.body_key_ph': 'e.g. notificationBodyKey',
    'notif.data_payload': 'Optional Data Payload (JSON)',
    'notif.data_payload_ph': '{"modelId": "llama-8b"}',
    'notif.fallback_section': 'Fallback Content',
    'notif.fallback_title': 'Fallback Title',
    'notif.fallback_title_ph': 'Fallback notification title',
    'notif.fallback_body': 'Fallback Body',
    'notif.fallback_body_ph': 'General message body to send',
    'notif.targeting': 'User Targeting',
    'notif.target_label': 'Target Group',
    'notif.target_placeholder': 'Select a group...',
    'notif.target_all': 'All Users',
    'notif.target_single': 'Single User (by UID)',
    'notif.target_level': 'By Subscription Level',
    'notif.uid_label': 'User UID',
    'notif.uid_ph': 'Firebase UID address',
    'notif.level_label': 'Minimum Subscription Level',
    'notif.level0': 'Free Members (Level 0)',
    'notif.level1': 'Plus Members (Level 1)',
    'notif.level2': 'Pro Members (Level 2)',
    'notif.level3': 'Ultra Members (Level 3)',
    'notif.mode': 'Delivery Mode',
    'notif.send_now': 'Send Now',
    'notif.schedule': 'Schedule',
    'notif.datetime': 'Date & Time',
    'notif.submit_btn': 'Send Notification',
    'notif.scheduled_title': 'Scheduled Notifications',
    'notif.no_scheduled': 'No scheduled notifications in queue.',
    'system.title': 'Server & System Settings',
    'system.desc': 'Control system infrastructure, toggle maintenance mode, or publish the attributions page.',
    'system.maintenance': 'Server Maintenance Mode',
    'system.maintenance_desc': 'Enabling maintenance mode stops new login requests. Logged-in users can continue in local mode.',
    'system.checking': 'Checking Status...',
    'system.loading_btn': 'Loading...',
    'system.live': 'Live',
    'system.maintenance_on': 'MAINTENANCE',
    'system.enable_maint': 'Enable Maintenance',
    'system.disable_maint': 'Disable Maintenance',
    'system.saving': 'SAVING',
    'system.retry': 'Retry',
    'system.maint_updated': 'Maintenance mode updated successfully.',
    'system.attributions': 'Publish Attributions Page',
    'system.attributions_desc': 'Use this trigger to rebuild and publish the attributions page after model or license updates.',
    'system.attributions_synced': 'Status: Synced',
    'system.attributions_pending': 'Status: Update Required',
    'system.attributions_btn': 'Update Attributions',
    'system.attributions_publish': 'Publish Changes',
    'system.attributions_uptodate': 'Up to Date',
    'system.attributions_trigger': 'TRIGGERING...',
    'system.attributions_retry': 'Retry Publish',
    'system.export': 'Export / Download Data',
    'system.export_desc': 'Download contributor lists, AI models, or news articles in your chosen format.',
    'system.export_type': 'Data to Export',
    'system.export_contributors': 'Contributor Applications',
    'system.export_manual_models': 'Curated AI Models',
    'system.export_all_models': 'All Models Database',
    'system.export_articles': 'Published Articles',
    'system.export_format': 'File Format',
    'system.export_json': 'JSON Format (.json)',
    'system.export_csv': 'CSV Format (Excel compatible .csv)',
    'system.export_btn': 'Compile & Download',
    'system.export_no_data': 'Selected data has not been loaded yet. Please visit the relevant tab first and wait for data to load.',
    'system.export_no_rows': 'No rows to export.',
    'system.export_success': 'Data exported successfully.',
    'system.export_downloaded': 'File downloaded successfully!',
    'system.gcs_backup': 'Google Cloud Storage (GCS) Backup',
    'system.gcs_desc': 'Automated GCS organization backup mechanism (via GitHub Actions) is currently <strong style="color: var(--accent-sage);">ACTIVE</strong> and operational.',
    'system.verify_user': 'Verify Contributor (Manual)',
    'system.verify_desc': 'Instantly verify a user\'s email address by providing their Email or UID.',
    'system.verify_id': 'User UID or Email',
    'system.verify_btn': 'Verify Email',
    'system.verify_success': 'User email successfully verified.',
    'system.remove_admin': 'Revoke Admin Access',
    'system.remove_admin_desc': 'Revoke an administrator\'s privileges using their email address.',
    'system.remove_email': 'Email Address',
    'system.remove_btn': 'Revoke Access',
    'system.remove_success': 'Admin access successfully revoked.',
    'system.admin_list': 'Active System Administrators',
    'system.loading_admins': 'Loading...',
    'system.error': 'Error',
    'dept.title': 'Department Access Permissions',
    'dept.desc': 'Configure which management tabs each department can access. Changes are saved automatically.',
    'dept.loading': 'Loading...',
    'dept.saved': 'Department permissions saved.',
    'dept.assign_title': 'Assign Department to User',
    'dept.assign_desc': 'Select the departments this user can access. Saving replaces the current department list.',
    'dept.assign_email': 'User Email',
    'dept.assign_dept': 'Departments',
    'dept.select_hint': 'Select at least one department.',
    'dept.users_title': 'Department Users',
    'dept.refresh': 'Refresh',
    'dept.search': 'Search name, email, or department...',
    'dept.empty': 'No users have a department assigned.',
    'dept.no_match': 'No users match this search.',
    'dept.load_error': 'Could not load users. Check the server function.',
    'dept.backend_required': 'The server function for multiple departments has not been deployed yet.',
    'dept.edit': 'Edit',
    'dept.select_dept': 'Select a department...',
    'dept.assign_btn': 'Assign Department',
    'dept.assign_success': 'Department assigned successfully.',
    'dept.group_ust': 'Upper Departments',
    'dept.group_orta': 'Middle Departments',
    'dept.group_alt': 'Lower Departments',
    'dept.essence': 'Essence',
    'dept.core': 'Core',
    'dept.senatus': 'Senatus',
    'dept.pulse': 'Pulse',
    'dept.chroma': 'Chroma',
    'dept.catalyst': 'Catalyst',
    'dept.envoy': 'Envoy',
    'dept.aero': 'Aero',
    'dept.array': 'Array',
    'dept.scout': 'Scout',
    'dept.vertest': 'Vertest',
    'dept.tensor': 'Tensor',
    'dept.curia': 'Curia',
    'panel.contributors.list': 'Applicants',
    'panel.system.adminRole': 'Grant Admin Role',
    'panel.contributors.vertexStatus': 'Toggle Vertex Status',
    'panel.models.manage': 'Add & Edit Models',
    'panel.models.library': 'Active Models & Tree',
    'panel.news.editor': 'Write News Article',
    'panel.news.published': 'Published Articles',
    'panel.notifications.sender': 'Send Push Notification',
    'panel.notifications.scheduled': 'Scheduled Notifications',
    'panel.subscriptions.assign': 'Assign Subscription',
    'panel.subscriptions.list': 'Assigned Subscriptions',
    'panel.system.deptPerms': 'Department Access Permissions',
    'panel.system.deptAssign': 'Assign Department to User',
    'panel.system.deptUsers': 'Department Users',
    'panel.system.manualVerify': 'Verify Contributor (Manual)',
    'panel.system.removeAdmin': 'Revoke Admin Role',
    'panel.system.adminList': 'Active Administrators',
    'panel.system.serverStatus': 'Server Maintenance Mode',
    'panel.system.attributions': 'Publish Attributions Page',
    'panel.system.exporter': 'Export Data',
    'perms.dept_col': 'Department',
    'perms.panel_menu': 'Panel settings',
    'perms.drag_hint': 'Move panel (drag & drop)',
    'perms.resize_hint': 'Resize',
    "perms.order_reset": "Reset this tab's panel order",
    'perms.menu_access': 'Access (per rank)',
    'perms.menu_content': 'Content settings',
    'perms.menu_chips': 'Filter categories',
    'perms.desc': 'Decide which sections each department can see and edit. Cells cycle through None / View / Edit; use the channel icon to fine-tune individual panels. Changes are saved automatically.',
    'perms.cycle_hint': 'Cycles None → View → Edit',
    'perms.level_none': 'None',
    'perms.level_read': 'View',
    'perms.level_write': 'Edit',
    'perms.preset_none': 'Close all channels',
    'perms.preset_read': 'Open all channels as read-only',
    'perms.preset_write': 'Grant full access to all channels',
    'perms.detail_btn': 'Fine-tune the panels of this channel',
    'perms.detail_title': 'Channel Permissions',
    'perms.detail_hint': 'Set a specific level for each panel of this channel. Cells without an arrow inherit the general (matrix) level; ↺ returns to it.',
    'perms.override_hint': 'This channel has panel-level overrides — click the channel icon for details',
    'perms.hidden_title': 'Hidden Field Groups',
    'perms.hidden_hint': 'Checked field groups are masked on the server for this department — they are never sent to the browser. Applies to the Contributors channel only.',
    'perms.hidden_contact': 'Contact info (email, phone)',
    'perms.hidden_age': 'Age',
    'perms.hidden_links': 'Social links',
    'perms.hidden_interview': 'Interview details',
    'perms.save_hint': "The server's saveDepartmentPermissions function is outdated. Copy adminsite-main/server/department-functions.cjs into your functions project and deploy it.",
    'perms.inherit_label': 'Inherited from general level',
    'perms.reset_btn': 'Return to general level',
    'contributors.edit_title': 'Edit Application',
    'contributors.save_btn': 'Save Changes',
    'contributors.cancel_btn': 'Cancel',
    'contributors.edit_updated': 'Application updated.',
    'contributors.field_name': 'Full Name',
    'contributors.field_email': 'Email',
    'contributors.field_phone': 'Phone',
    'contributors.field_age': 'Age',
    'contributors.field_department': 'Department',
    'contributors.field_language': 'Language',
    'contributors.field_linkedin': 'LinkedIn',
    'contributors.field_github': 'GitHub',
    'contributors.field_interview': 'Interview Date',
    'contributors.field_about': 'About',
    'contributors.field_interview_details': 'Interview Details',
    'nav.chat': 'Chat',
    'chat.title': 'Chat',
    'chat.desc': 'Department channels, task tracking and @mention notifications.',
    'chat.channels': 'Channels',
    'chat.no_channels': 'No channels yet.',
    'toast.dismiss_hint': 'Click to dismiss the notification',
    'chat.login_hint': 'Sign in to see the channels.',
    'chat.loading': 'Loading...',
    'chat.empty': 'No messages in this channel yet.',
    'chat.select_hint': 'Select a channel.',
    'chat.readonly': 'Only administrators can post in this channel.',
    'chat.open_all': 'Open to all departments',
    'chat.placeholder': 'Write a message — mention @Department or @email',
    'chat.as_task': 'Task/Issue',
    'chat.task_open': 'Open',
    'chat.task_done': 'Resolved',
    'chat.task_done_btn': 'Mark resolved',
    'chat.task_reopen': 'Reopen',
    'chat.form_create': 'Create Channel',
    'chat.form_edit': 'Edit Channel',
    'chat.name_required': 'Channel name is required.',
    'chat.created': 'Channel created.',
    'chat.updated': 'Channel updated.',
    'user_menu.admin': 'Admin',
    'user_menu.profile': 'Profile',
    'user_menu.theme': 'Toggle Theme',
    'nav.subscriptions': 'Subscription',
    'subs.title': 'Subscription Management',
    'subs.desc': 'Manually assign Plus, Pro or Ultra subscriptions to user accounts and track active grants.',
    'subs.form_title': 'Assign Subscription to User',
    'subs.form_desc': "Enter the user's account email to automatically grant the selected subscription instantly; the duration can be at most 1 year.",
    'subs.username_label': 'Username',
    'subs.username_ph': 'In-app username',
    'subs.username_hint': 'For display in the list; the grant is matched by email.',
    'subs.email_label': 'Account Email (Gmail)',
    'subs.email_hint': 'The user must be registered with this email address.',
    'subs.plan_label': 'Subscription Tier',
    'subs.plan_plus': 'Plus Membership',
    'subs.plan_pro': 'Pro Membership',
    'subs.plan_ultra': 'Ultra Membership',
    'subs.end_label': 'End Time (Max 1 Year)',
    'subs.end_label_short': 'Ends',
    'subs.duration_hint': 'The subscription starts instantly and can be set at most 1 year ahead.',
    'subs.assign_btn': 'Assign Subscription',
    'subs.assigning': 'ASSIGNING',
    'subs.assign_success': 'Subscription assigned successfully.',
    'subs.expires_past': 'The end time must be a date in the future.',
    'subs.max_one_year': 'The subscription duration cannot exceed 1 year.',
    'subs.list_title': 'Assigned Subscriptions',
    'subs.refresh': 'Refresh',
    'subs.search': 'Search name, email, or tier...',
    'subs.load_hint': 'Press the Refresh button to load the list.',
    'subs.list_loading': 'Loading subscriptions...',
    'subs.empty': 'No assigned subscriptions found.',
    'subs.no_match': 'No subscriptions match this search.',
    'subs.load_error': 'Could not load subscriptions. Check the server function.',
    'subs.remove_btn': 'Remove',
    'subs.remove_confirm': 'Are you sure you want to remove this subscription?',
    'subs.removing': 'REMOVING',
    'subs.remove_success': 'Subscription removed successfully.',
    'subs.badge_active': 'Active',
    'subs.badge_expired': 'Expired',
    'subs.bulk_toggle': 'Bulk Assignment',
    'subs.bulk_hint': 'Paste the email list: separate with commas, semicolons, spaces or line breaks — the server parses the input and assigns it in batches of 50 with intervals. The tier and end time come from the fields above.',
    'subs.bulk_label': 'Email List',
    'subs.bulk_placeholder': 'user1@gmail.com, user2@gmail.com, user3@gmail.com ...',
    'subs.bulk_btn': 'Assign in Bulk',
    'subs.bulk_running': 'BULK ASSIGNMENT RUNNING...',
    'subs.bulk_started': 'Bulk assignment started; this may take a few minutes depending on the number of emails.',
    'subs.bulk_granted': 'accounts assigned',
    'subs.bulk_failed': 'failed',
    'subs.bulk_failed_title': 'Addresses that could not be assigned',
    'subs.bulk_invalid_title': 'Invalid entries',
    'profile.title': 'My Profile',
    'profile.desc': 'View your account details and panel access.',
    'profile.display_name': 'Display name',
    'profile.save': 'Save Profile',
    'profile.saved': 'Profile saved.',
    'profile.access': 'Access Details',
    'profile.role': 'Role',
    'profile.departments': 'Departments',
    'profile.uid': 'User ID',
    'profile.admin': 'Administrator',
    'profile.member': 'Department member',
    'profile.none': 'None assigned',
    'profile.menu_btn': 'Menu',
    'profile.uid_copied': 'ID copied to clipboard.',
    'profile.uid_copied_fail': 'Copy failed.',
    'profile.menu_soon': 'This option will be available soon.',
    'profile.menu_1': 'Account Settings',
    'profile.menu_2': 'Notification Preferences',
    'profile.menu_3': 'Security',
    'profile.menu_4': 'Session History',
    'profile.menu_5': 'Theme & Appearance',
    'profile.menu_6': 'Language Preferences',
    'profile.menu_7': 'Help & Support',
    'profile.menu_8': 'Sign Out',
    'profile.perms_title': 'Permission Summary',
    'auth.not_admin': 'You are not authorized to access this panel.',
    'auth.login_failed': 'Login Failed:',
    'auth.enter_credentials': 'Please enter both email and password.',
    'auth.session_expired': 'Authentication session expired. Please log in again.',
    'auth.try_again': 'Try Again',
    'template.group.system': 'System & Offers',
    'template.group.engagement': 'User Engagement',
    'template.group.fun': 'Fun & Jokes',
    'template.group.tech': 'Technical Details',
    'template.group.special': 'Special Days',
    'template.newModel': 'New Model Added',
    'template.newFeature': 'New Feature Added',
    'template.upsellFeature': 'Subscription Campaign',
    'template.appUpdate': 'App Update Notice',
    'template.rateApp': 'Rate the App',
    'template.referral': 'Refer a Friend',
    'template.socialMedia': 'Social Media Engagement',
    'template.comeback': 'Comeback Call (General)',
    'template.longTimeNoSee': 'Long Time No See',
    'template.howAreYou': 'Check In',
    'template.goodMorning': 'Good Morning Message',
    'template.goodNight': 'Good Night Message',
    'template.randomFact': 'Random Fact',
    'template.showerThought': 'Shower Thoughts',
    'template.fortuneCookie': 'Fortune Cookie',
    'template.hackerJoke': 'Developer Jokes',
    'template.pirate': 'Pirate Mode',
    'template.trollAnime': 'Troll (Anime)',
    'template.trollAiRebellion': 'Troll (AI Rebellion)',
    'template.singularity': 'Singularity',
    'template.detectiveCase': 'Detective Story',
    'template.originStory': 'Story Origin',
    'template.rejectionStory': 'Rejection Memory',
    'template.cooking': 'Chef\'s Recipe',
    'template.existential': 'Existential Crisis',
    'template.openSource': 'Open Source Love',
    'template.offlineReady': 'Offline Mode Ready',
    'template.customModel': 'Bring Your Own Model',
    'template.dynamicChat': 'Dynamic Chat Rooms',
    'template.ggufSupport': 'GGUF Support Active',
    'template.themeCustomization': 'Theme Customization',
    'template.homeworkHelper': 'Homework Assistant Intro',
    'template.lowBattery': 'Low Battery Saver Mode',
    'template.newYear': 'New Year Greeting',
    'template.valentinesDay': 'Valentine\'s Day',
    'template.ataturkRemembrance': 'Nov 10 Ataturk Remembrance',
    'template.mothersDay': 'Mother\'s Day',
    'template.fathersDay': 'Father\'s Day',
  }
};

let currentLang = localStorage.getItem('siteLang') || 'tr';

export function __(key) {
  return LANG[currentLang]?.[key] || LANG['tr']?.[key] || key;
}

// Make __ available globally for inline scripts
window.__ = __;

export function getLang() {
  return currentLang;
}

export function setLang(lang) {
  if (LANG[lang]) {
    currentLang = lang;
    localStorage.setItem('siteLang', lang);
    document.documentElement.lang = lang;
    translatePage();
    dispatchLangChange();
  }
}

const langChangeCallbacks = [];

export function onLangChange(callback) {
  langChangeCallbacks.push(callback);
}

function dispatchLangChange() {
  langChangeCallbacks.forEach(cb => {
    try { cb(currentLang); } catch (e) { console.error(e); }
  });
}

export function translatePage() {
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.getAttribute('data-i18n');
    const translation = __(key);
    if (translation.includes('<')) {
      el.innerHTML = translation;
    } else {
      el.textContent = translation;
    }
  });
  document.querySelectorAll('[data-i18n-placeholder]').forEach(el => {
    const key = el.getAttribute('data-i18n-placeholder');
    el.placeholder = __(key);
  });
  document.querySelectorAll('[data-i18n-title]').forEach(el => {
    const key = el.getAttribute('data-i18n-title');
    el.title = __(key);
  });
  document.querySelectorAll('[data-i18n-value]').forEach(el => {
    const key = el.getAttribute('data-i18n-value');
    el.value = __(key);
  });
  // Update page title
  const titleKey = document.querySelector('title')?.getAttribute('data-i18n');
  if (titleKey) document.title = __(titleKey);
  const metaDesc = document.querySelector('meta[name="description"]');
  if (metaDesc?.getAttribute('data-i18n')) {
    metaDesc.content = __(metaDesc.getAttribute('data-i18n'));
  }
  // Update select option text content
  document.querySelectorAll('select[data-i18n-options]').forEach(select => {
    Array.from(select.options).forEach(opt => {
      const key = opt.getAttribute('data-i18n');
      if (key) opt.textContent = __(key);
    });
  });
}
