const LANG = {
  tr: {
    'lang.name': 'Türkçe',
    'lang.flag': 'TR',
    'page.title': 'Vertex Kontrol - Yönetici Paneli',
    'page.desc': 'Vertex içerikleri, kullanıcı yönetimi ve sistem yönetimi için merkezi kontrol paneli.',
    'loader.text': 'Vertex Kontrol Başlatılıyor',
    'login.title': 'VERTEX CONTROL',
    'login.subtitle': 'Sistem Yönetim Modülü',
    'login.email': 'E-posta Adresiniz',
    'login.password': 'Şifreniz',
    'login.btn': 'Oturum Aç',
    'login.or': 'veya',
    'header.brand': 'VERTEX',
    'header.system': 'Sistem Portal',
    'header.theme': 'Temayı Değiştir',
    'header.logout': 'Çıkış',
    'nav.contributors': 'Katılımcı',
    'nav.models': 'Modeller',
    'nav.news': 'Haberler',
    'nav.notifications': 'Bildirim',
    'nav.system': 'Sistem',
    'contributors.title': 'Katılımcı Yönetimi & Yetkiler',
    'contributors.desc': 'Vertex topluluk üyelerini inceleyin, onaylayın ve yönetici yetkilerini yönetin.',
    'contributors.section': 'Başvuran Adaylar & Üyeler',
    'contributors.refresh': 'Yenile',
    'contributors.filter.all': 'Tümü',
    'contributors.filter.verified': 'Onaylılar',
    'contributors.filter.unverified': 'Onay Bekleyenler',
    'contributors.filter.age14': '14-15 Yaş',
    'contributors.filter.age16': '16-17 Yaş',
    'contributors.filter.age18': '18+ Yaş',
    'contributors.filter.linkedin': 'LinkedIn',
    'contributors.filter.github': 'GitHub',
    'contributors.search': 'Listede isim, e-posta veya biyografi ara...',
    'contributors.load_hint': 'Listeyi yüklemek için Yenile butonuna basın.',
    'contributors.loading': 'Yükleniyor...',
    'contributors.load_error': 'Katılımcılar yüklenemedi.',
    'contributors.empty': 'Katılımcı bulunamadı.',
    'contributors.no_match': 'Kriterlere uyan başvuru bulunamadı.',
    'contributors.search_no_match': 'Arama sonucuna uygun katılımcı bulunamadı.',
    'contributors.delete_confirm': 'Emin misiniz? Başvuru tamamen silinecek.',
    'contributors.deleted': 'Katılımcı başarıyla silindi.',
    'contributors.verified_label': 'Doğrulandı',
    'contributors.unverified_label': 'Doğrulanmadı',
    'contributors.verify_updated': 'Doğrulama durumu güncellendi!',
    'admin.title': 'Yönetici Rolü Tanımla',
    'admin.desc': 'Doğrulanmış bir Vertex üyesinin e-posta adresini girerek yönetici kontrol yetkisi tanımlayın.',
    'admin.email_label': 'Kullanıcı E-postası',
    'admin.email_placeholder': 'kullanici@vertexishere.com',
    'admin.email_hint': 'Kullanıcı sisteme kayıtlı olmalıdır.',
    'admin.grant_btn': 'Yönetici Yetkisi Ver',
    'admin.granting': 'YETKİ VERİLİYOR',
    'admin.grant_success': 'Yönetici rolü başarıyla verildi.',
    'models.title': 'Yapay Zeka Modelleri',
    'models.desc': 'Uygulamada yayında olan çevrimdışı (On-Device) ve rol yapma yapay zeka modellerini yönetin.',
    'models.form_title': 'Model Ekleme ve Düzenleme',
    'models.classification': 'Model Sınıflandırması',
    'models.roleplay': 'Rol Yapma',
    'models.offline': 'Çevrimdışı',
    'models.producer': 'Geliştirici Firma',
    'models.producer_ph': 'Ör. Google, Meta',
    'models.id': 'Model Kimliği (ID)',
    'models.id_ph': 'Ör. gemma-2b-it',
    'models.card_info': 'Arayüz Kart Bilgileri (İngilizce)',
    'models.title_field': 'Model Adı (Title)',
    'models.title_ph': 'Görüntülenecek başlık',
    'models.summary': 'Özet (Summary)',
    'models.summary_ph': 'Karttaki kısa özet açıklaması',
    'models.description': 'Tam Detaylı Açıklama (Description)',
    'models.description_ph': 'Model yetenekleri hakkında detaylı metin',
    'models.roleplay_config': 'Rol Yapma Konfigürasyonu',
    'models.system_prompt': 'Sistem Promptu (System Role)',
    'models.system_prompt_ph': 'Karakterin uyacağı yönerge promptu',
    'models.offline_config': 'Çevrimdışı Bağlantılar & Donanım',
    'models.gguf_url': 'GGUF HuggingFace İndirme Adresi',
    'models.gguf_ph': 'https://huggingface.co/.../*.gguf',
    'models.file_size': 'Dosya Boyutu (MB)',
    'models.file_size_ph': 'MB cinsinden',
    'models.ram': 'Gereken RAM (MB)',
    'models.ram_ph': 'MB cinsinden',
    'models.io_types': 'Girdi ve Çıktı Tipleri',
    'models.input_types': 'Girdi Tipleri',
    'models.output_types': 'Çıktı Tipleri',
    'models.image': 'Görsel',
    'models.video': 'Video',
    'models.audio': 'Ses',
    'models.file': 'Dosya',
    'models.text': 'Metin',
    'models.license_section': 'Lisans & Kaynak',
    'models.creator': 'Geliştirici',
    'models.license_type': 'Lisans Türü',
    'models.license_type_ph': 'Lisans ismi',
    'models.source': 'Kaynak',
    'models.license_url': 'Lisans Linki',
    'models.license_url_ph': 'Lisans URL adresi',
    'models.template_section': 'Şablon Kuralları (Prompter)',
    'models.template_select': 'Hazır Şablon Formatı',
    'models.template_none': '-- Şablon Seçilmedi --',
    'models.token_system_start': 'Sistem Başlangıç',
    'models.token_system_end': 'Sistem Bitiş',
    'models.token_user_start': 'Kullanıcı Başlangıç',
    'models.token_user_end': 'Kullanıcı Bitiş',
    'models.token_assistant_start': 'Asistan Başlangıç',
    'models.token_assistant_end': 'Asistan Bitiş',
    'models.token_stop': 'Durdurma Belirteçleri',
    'models.token_stop_ph': '<|im_end|>, </s>',
    'models.token_ignore': 'Yok Sayılacak Regex',
    'models.token_ignore_ph': '^[Düşünme Adımları]...$',
    'models.image_section': 'Resim Dosyası',
    'models.image_label': 'Model Temsili Resmi',
    'models.save_btn': 'Değişiklikleri Kaydet',
    'models.cancel_btn': 'İptal Et',
    'models.active_models': 'Aktif Modeller',
    'models.offline_count': 'Çevrimdışı:',
    'models.roleplay_count': 'Rol Yapma:',
    'models.no_models': 'Kayıtlı model bulunamadı.',
    'models.all_models': 'Tüm Modeller Ağacı',
    'models.loading': 'Yükleniyor...',
    'news.title': 'Haberler & Duyurular',
    'news.desc': 'Mobil uygulama ana sayfasındaki haber akışında görünecek makaleleri yayınlayın.',
    'news.form_title': 'Haber Duyurusu Yaz',
    'news.tr_section': 'Türkçe Yayın İçeriği',
    'news.tr_title': 'Başlık (TR)',
    'news.tr_title_ph': 'Haber başlığı',
    'news.tr_summary': 'Özet (TR)',
    'news.tr_summary_ph': 'Haber akış kartındaki özet',
    'news.tr_content': 'Detay (TR)',
    'news.tr_content_ph': 'Makale detaylı içeriği (Markdown destekler)',
    'news.tr_cover': 'Kapak Fotoğrafı (TR)',
    'news.en_section': 'English Content (İngilizce)',
    'news.en_title': 'Title (EN)',
    'news.en_title_ph': 'Article Title',
    'news.en_summary': 'Summary (EN)',
    'news.en_summary_ph': 'Short description summary',
    'news.en_content': 'Body (EN)',
    'news.en_content_ph': 'Detailed content details',
    'news.en_cover': 'Cover Image (EN)',
    'news.meta_section': 'Meta Veri & Referanslar',
    'news.tags': 'Etiketler',
    'news.tags_ph': 'Ör. guncelleme, topluluk (virgülle ayırın)',
    'news.references': 'Kaynak Bağlantıları (URL)',
    'news.references_ph': 'Her satıra bir adet bağlantı gelecek şekilde',
    'news.publish_btn': 'Haber Makalesini Yayınla',
    'news.active_articles': 'Aktif Yayındaki Haberler',
    'news.no_articles': 'Yayınlanmış haber makalesi bulunamadı.',
    'notif.title': 'Anlık Bildirimler',
    'notif.desc': 'Vertex kullanıcılarına hedeflenmiş veya zamanlanmış anlık push bildirimleri gönderin.',
    'notif.form_title': 'Push Bildirim Gönder / Ayarla',
    'notif.template_section': 'Hazır Şablon & Anahtarlar',
    'notif.template_label': 'Hazır Şablonlar',
    'notif.template_none': '-- Şablon Kullanma --',
    'notif.title_key': 'Başlık Anahtarı (Title Key)',
    'notif.title_key_ph': 'Ör. notificationTitleKey',
    'notif.body_key': 'Gövde Anahtarı (Body Key)',
    'notif.body_key_ph': 'Ör. notificationBodyKey',
    'notif.data_payload': 'İsteğe Bağlı Veri Yükü (JSON)',
    'notif.data_payload_ph': '{"modelId": "llama-8b"}',
    'notif.fallback_section': 'Yedek Bildirim İçeriği',
    'notif.fallback_title': 'Genel Başlık',
    'notif.fallback_title_ph': 'Yedek bildirim başlığı',
    'notif.fallback_body': 'Genel Mesaj Gövdesi',
    'notif.fallback_body_ph': 'Gönderilecek genel mesaj metni',
    'notif.targeting': 'Kullanıcı Hedefleme',
    'notif.target_label': 'Alıcı Grubu',
    'notif.target_placeholder': 'Bir grup seçin...',
    'notif.target_all': 'Tüm Kullanıcılar',
    'notif.target_single': 'Tek Bir Kullanıcı (UID ile)',
    'notif.target_level': 'Abonelik Seviyesine Göre',
    'notif.uid_label': 'Kullanıcı UID',
    'notif.uid_ph': 'Firebase UID adresi',
    'notif.level_label': 'Minimum Abonelik Düzeyi',
    'notif.level0': 'Ücretsiz Üyeler (Level 0)',
    'notif.level1': 'Plus Üyeler (Level 1)',
    'notif.level2': 'Pro Üyeler (Level 2)',
    'notif.level3': 'Ultra Üyeler (Level 3)',
    'notif.mode': 'Gönderim Modu',
    'notif.send_now': 'Hemen Gönder',
    'notif.schedule': 'Zamanla',
    'notif.datetime': 'Tarih ve Saat',
    'notif.submit_btn': 'Bildirimi Gönder',
    'notif.scheduled_title': 'Zamanlanmış Bildirimler',
    'notif.no_scheduled': 'Kuyrukta bekleyen bildirim bulunamadı.',
    'system.title': 'Sunucu & Sistem Ayarları',
    'system.desc': 'Sistem altyapısını kontrol edin, bakım modunu açıp kapatın veya atıflar sayfasını yayınlayın.',
    'system.maintenance': 'Sunucu Bakım Modu',
    'system.maintenance_desc': 'Sunucu bakım modunu açmak yeni giriş işlemlerini durdurur. Giriş yapmış kullanıcılar yerel modda devam edebilir.',
    'system.checking': 'Durum Kontrol Ediliyor...',
    'system.loading_btn': 'Yükleniyor...',
    'system.live': 'Canlı',
    'system.maintenance_on': 'BAKIM',
    'system.enable_maint': 'Bakım Modunu Aç',
    'system.disable_maint': 'Bakım Modunu Kapat',
    'system.saving': 'KAYDEDİLİYOR',
    'system.retry': 'Tekrar Dene',
    'system.maint_updated': 'Bakım modu başarıyla güncellendi.',
    'system.attributions': 'Atıflar Sayfasını Yayınla',
    'system.attributions_desc': 'Model veya lisans güncellemelerinin ardından atıflar sayfasını tekrar derleyip yayınlamak için bu tetikleyiciyi kullanın.',
    'system.attributions_synced': 'Durum: Güncel',
    'system.attributions_pending': 'Durum: Güncelleme Gerekli',
    'system.attributions_btn': 'Atıf Sayfasını Güncelle',
    'system.attributions_publish': 'Değişiklikleri Yayınla',
    'system.attributions_uptodate': 'Güncel',
    'system.attributions_trigger': 'TETİKLENİYOR...',
    'system.attributions_retry': 'Tekrar Dene',
    'system.export': 'Verileri Dışa Aktar / İndir',
    'system.export_desc': 'Sistemde yüklü olan katılımcı listelerini, AI modellerini veya haber makalelerini seçtiğiniz formatta yerel olarak bilgisayarınıza indirebilirsiniz.',
    'system.export_type': 'Dışa Aktarılacak Veri',
    'system.export_contributors': 'Katılımcı Başvuruları',
    'system.export_manual_models': 'Eklenen AI Modelleri (Küratörlü)',
    'system.export_all_models': 'Tüm Modeller Veritabanı',
    'system.export_articles': 'Yayınlanan Haberler',
    'system.export_format': 'Dosya Formatı',
    'system.export_json': 'JSON Formatı (.json)',
    'system.export_csv': 'CSV Formatı (Excel uyumlu .csv)',
    'system.export_btn': 'Veriyi Derle ve İndir',
    'system.export_no_data': 'Seçtiğiniz veriler henüz yüklenmemiş. Lütfen önce ilgili sekmesini ziyaret edip verilerin gelmesini bekleyin.',
    'system.export_no_rows': 'Dışa aktarılacak satır bulunamadı.',
    'system.export_success': 'Veriler başarıyla dışa aktarıldı.',
    'system.export_downloaded': 'Dosya başarıyla indirildi!',
    'system.gcs_backup': 'Google Cloud Storage (GCS) Yedekleme',
    'system.gcs_desc': 'Otomatik GCS organizasyon yedekleme mekanizması (GitHub Actions üzerinden) şu anda <strong style="color: var(--accent-sage);">AKTİF</strong> ve çalışır durumda.',
    'system.verify_user': 'Katılımcı Doğrula (Manuel)',
    'system.verify_desc': 'Bir kullanıcının e-posta adresini (E-posta veya UID girerek) anında doğrulanmış durumuna getirin.',
    'system.verify_id': 'Kullanıcı UID veya E-posta',
    'system.verify_btn': 'Doğrula',
    'system.verify_success': 'Kullanıcı e-postası başarıyla doğrulandı.',
    'system.remove_admin': 'Yönetici Yetkisi Al',
    'system.remove_admin_desc': 'Bir sistem yöneticisinin (Admin) yetkilerini e-posta adresi üzerinden iptal edin.',
    'system.remove_email': 'E-posta Adresi',
    'system.remove_btn': 'Yetkiyi İptal Et',
    'system.remove_success': 'Yönetici yetkisi başarıyla iptal edildi.',
    'system.admin_list': 'Aktif Sistem Yöneticileri',
    'system.loading_admins': 'Yükleniyor...',
    'system.error': 'Hata',
    'auth.not_admin': 'Bu panele erişim yetkiniz bulunmamaktadır.',
    'auth.login_failed': 'Giriş başarısız:',
    'auth.enter_credentials': 'Lütfen e-posta ve şifrenizi girin.',
    'auth.session_expired': 'Oturum süreniz doldu. Lütfen tekrar giriş yapın.',
    'auth.try_again': 'Tekrar Dene',
    'template.group.system': 'Sistem & Teklifler',
    'template.group.engagement': 'Kullanıcı Etkileşimi',
    'template.group.fun': 'Eğlenceli & Şakalar',
    'template.group.tech': 'Teknik Detaylar',
    'template.group.special': 'Özel Günler',
    'template.newModel': 'Yeni Model Eklendi',
    'template.newFeature': 'Yeni Özellik Eklendi',
    'template.upsellFeature': 'Abonelik Kampanyası',
    'template.appUpdate': 'Uygulama Güncelleme Uyarısı',
    'template.rateApp': 'Uygulamayı Puanla',
    'template.referral': 'Arkadaşına Öner',
    'template.socialMedia': 'Sosyal Medya Katılımı',
    'template.comeback': 'Geri Dönüş Çağrısı (Genel)',
    'template.longTimeNoSee': 'Uzun Süre Giriş Yapmayanlar',
    'template.howAreYou': 'Hal Hatır Sorma',
    'template.goodMorning': 'Günaydın Mesajı',
    'template.goodNight': 'İyi Geceler Mesajı',
    'template.randomFact': 'İlginç Bilgi',
    'template.showerThought': 'Duş Düşünceleri',
    'template.fortuneCookie': 'Şans Kurabiyesi',
    'template.hackerJoke': 'Yazılımcı Şakaları',
    'template.pirate': 'Korsan Modu',
    'template.trollAnime': 'Troll (Anime)',
    'template.trollAiRebellion': 'Troll (Yapay Zeka İsyanı)',
    'template.singularity': 'Singularity',
    'template.detectiveCase': 'Dedektif Hikayesi',
    'template.originStory': 'Hikaye Başlangıcı',
    'template.rejectionStory': 'Reddedilme Anısı',
    'template.cooking': 'Şefin Tarifi',
    'template.existential': 'Varoluşsal Kriz',
    'template.openSource': 'Açık Kaynak Sevgisi',
    'template.offlineReady': 'Çevrimdışı Çalışma Hazır',
    'template.customModel': 'Kendi Modelini Kur',
    'template.dynamicChat': 'Dinamik Sohbet Odaları',
    'template.ggufSupport': 'GGUF Desteği Aktif',
    'template.themeCustomization': 'Tema Özelleştirme',
    'template.homeworkHelper': 'Ödev Asistanı Tanıtımı',
    'template.lowBattery': 'Düşük Batarya Tasarruf Modu',
    'template.newYear': 'Yılbaşı Tebriği',
    'template.valentinesDay': 'Sevgililer Günü',
    'template.ataturkRemembrance': '10 Kasım Atatürk\'ü Anma',
    'template.mothersDay': 'Anneler Günü',
    'template.fathersDay': 'Babalar Günü',
  },

  en: {
    'lang.name': 'English',
    'lang.flag': 'EN',
    'page.title': 'Vertex Control - Admin Panel',
    'page.desc': 'Central control panel for Vertex content, user management and system administration.',
    'loader.text': 'Starting Vertex Control',
    'login.title': 'VERTEX CONTROL',
    'login.subtitle': 'System Administration Module',
    'login.email': 'Your Email Address',
    'login.password': 'Your Password',
    'login.btn': 'Sign In',
    'login.or': 'or',
    'header.brand': 'VERTEX',
    'header.system': 'System Portal',
    'header.theme': 'Toggle Theme',
    'header.logout': 'Logout',
    'nav.contributors': 'Contributors',
    'nav.models': 'Models',
    'nav.news': 'News',
    'nav.notifications': 'Notifications',
    'nav.system': 'System',
    'contributors.title': 'Contributor Management & Permissions',
    'contributors.desc': 'Review Vertex community members, approve them and manage admin permissions.',
    'contributors.section': 'Applicants & Members',
    'contributors.refresh': 'Refresh',
    'contributors.filter.all': 'All',
    'contributors.filter.verified': 'Verified',
    'contributors.filter.unverified': 'Pending',
    'contributors.filter.age14': 'Age 14-15',
    'contributors.filter.age16': 'Age 16-17',
    'contributors.filter.age18': 'Age 18+',
    'contributors.filter.linkedin': 'LinkedIn',
    'contributors.filter.github': 'GitHub',
    'contributors.search': 'Search by name, email or bio...',
    'contributors.load_hint': 'Press Refresh to load the list.',
    'contributors.loading': 'Loading contributors...',
    'contributors.load_error': 'Failed to load contributors.',
    'contributors.empty': 'No contributors found.',
    'contributors.no_match': 'No applications match the criteria.',
    'contributors.search_no_match': 'No contributors match your search.',
    'contributors.delete_confirm': 'Are you sure? The application will be permanently deleted.',
    'contributors.deleted': 'Contributor deleted successfully.',
    'contributors.verified_label': 'Verified',
    'contributors.unverified_label': 'Unverified',
    'contributors.verify_updated': 'Verification status updated!',
    'admin.title': 'Assign Admin Role',
    'admin.desc': 'Grant admin control privileges by entering the email of a verified Vertex member.',
    'admin.email_label': 'User Email',
    'admin.email_placeholder': 'user@vertexishere.com',
    'admin.email_hint': 'User must be registered in the system.',
    'admin.grant_btn': 'Grant Admin Role',
    'admin.granting': 'GRANTING',
    'admin.grant_success': 'Admin role granted successfully.',
    'models.title': 'AI Models',
    'models.desc': 'Manage online roleplay and offline (On-Device) AI models published in the app.',
    'models.form_title': 'Add / Edit Model',
    'models.classification': 'Model Classification',
    'models.roleplay': 'Roleplay',
    'models.offline': 'Offline',
    'models.producer': 'Producer',
    'models.producer_ph': 'e.g. Google, Meta',
    'models.id': 'Model ID',
    'models.id_ph': 'e.g. gemma-2b-it',
    'models.card_info': 'Card Details (English)',
    'models.title_field': 'Model Title',
    'models.title_ph': 'Display title',
    'models.summary': 'Summary',
    'models.summary_ph': 'Short card summary',
    'models.description': 'Full Description',
    'models.description_ph': 'Detailed text about model capabilities',
    'models.roleplay_config': 'Roleplay Configuration',
    'models.system_prompt': 'System Prompt (System Role)',
    'models.system_prompt_ph': 'Character instruction prompt',
    'models.offline_config': 'Offline Connections & Hardware',
    'models.gguf_url': 'GGUF HuggingFace Download URL',
    'models.gguf_ph': 'https://huggingface.co/.../*.gguf',
    'models.file_size': 'File Size (MB)',
    'models.file_size_ph': 'In MB',
    'models.ram': 'Required RAM (MB)',
    'models.ram_ph': 'In MB',
    'models.io_types': 'Input & Output Types',
    'models.input_types': 'Input Types',
    'models.output_types': 'Output Types',
    'models.image': 'Image',
    'models.video': 'Video',
    'models.audio': 'Audio',
    'models.file': 'File',
    'models.text': 'Text',
    'models.license_section': 'License & Source',
    'models.creator': 'Creator',
    'models.license_type': 'License Type',
    'models.license_type_ph': 'License name',
    'models.source': 'Source',
    'models.license_url': 'License URL',
    'models.license_url_ph': 'License URL address',
    'models.template_section': 'Template Rules (Prompter)',
    'models.template_select': 'Preset Template Format',
    'models.template_none': '-- No Template --',
    'models.token_system_start': 'System Start',
    'models.token_system_end': 'System End',
    'models.token_user_start': 'User Start',
    'models.token_user_end': 'User End',
    'models.token_assistant_start': 'Assistant Start',
    'models.token_assistant_end': 'Assistant End',
    'models.token_stop': 'Stop Tokens',
    'models.token_stop_ph': '<|im_end|>, </s>',
    'models.token_ignore': 'Ignore Regex',
    'models.token_ignore_ph': '^[Thinking Steps]...$',
    'models.image_section': 'Image File',
    'models.image_label': 'Model Image',
    'models.save_btn': 'Save Changes',
    'models.cancel_btn': 'Cancel',
    'models.active_models': 'Active Models',
    'models.offline_count': 'Offline:',
    'models.roleplay_count': 'Roleplay:',
    'models.no_models': 'No models found.',
    'models.all_models': 'All Models Tree',
    'models.loading': 'Loading...',
    'news.title': 'News & Announcements',
    'news.desc': 'Publish articles that will appear in the news feed on the mobile app home page.',
    'news.form_title': 'Write News Article',
    'news.tr_section': 'Turkish Content',
    'news.tr_title': 'Title (TR)',
    'news.tr_title_ph': 'News title',
    'news.tr_summary': 'Summary (TR)',
    'news.tr_summary_ph': 'News card summary',
    'news.tr_content': 'Content (TR)',
    'news.tr_content_ph': 'Detailed article content (Markdown supported)',
    'news.tr_cover': 'Cover Image (TR)',
    'news.en_section': 'English Content',
    'news.en_title': 'Title (EN)',
    'news.en_title_ph': 'Article Title',
    'news.en_summary': 'Summary (EN)',
    'news.en_summary_ph': 'Short description summary',
    'news.en_content': 'Body (EN)',
    'news.en_content_ph': 'Detailed content details',
    'news.en_cover': 'Cover Image (EN)',
    'news.meta_section': 'Metadata & References',
    'news.tags': 'Tags',
    'news.tags_ph': 'e.g. update, community (comma separated)',
    'news.references': 'Reference Links (URL)',
    'news.references_ph': 'One link per line',
    'news.publish_btn': 'Publish Article',
    'news.active_articles': 'Published Articles',
    'news.no_articles': 'No published articles found.',
    'notif.title': 'Push Notifications',
    'notif.desc': 'Send targeted or scheduled push notifications to Vertex users.',
    'notif.form_title': 'Send / Schedule Notification',
    'notif.template_section': 'Templates & Keys',
    'notif.template_label': 'Template Selection',
    'notif.template_none': '-- No Template --',
    'notif.title_key': 'Title Key',
    'notif.title_key_ph': 'e.g. notificationTitleKey',
    'notif.body_key': 'Body Key',
    'notif.body_key_ph': 'e.g. notificationBodyKey',
    'notif.data_payload': 'Optional Data Payload (JSON)',
    'notif.data_payload_ph': '{"modelId": "llama-8b"}',
    'notif.fallback_section': 'Fallback Content',
    'notif.fallback_title': 'Fallback Title',
    'notif.fallback_title_ph': 'Fallback notification title',
    'notif.fallback_body': 'Fallback Body',
    'notif.fallback_body_ph': 'General message body to send',
    'notif.targeting': 'User Targeting',
    'notif.target_label': 'Target Group',
    'notif.target_placeholder': 'Select a group...',
    'notif.target_all': 'All Users',
    'notif.target_single': 'Single User (by UID)',
    'notif.target_level': 'By Subscription Level',
    'notif.uid_label': 'User UID',
    'notif.uid_ph': 'Firebase UID address',
    'notif.level_label': 'Minimum Subscription Level',
    'notif.level0': 'Free Members (Level 0)',
    'notif.level1': 'Plus Members (Level 1)',
    'notif.level2': 'Pro Members (Level 2)',
    'notif.level3': 'Ultra Members (Level 3)',
    'notif.mode': 'Delivery Mode',
    'notif.send_now': 'Send Now',
    'notif.schedule': 'Schedule',
    'notif.datetime': 'Date & Time',
    'notif.submit_btn': 'Send Notification',
    'notif.scheduled_title': 'Scheduled Notifications',
    'notif.no_scheduled': 'No scheduled notifications in queue.',
    'system.title': 'Server & System Settings',
    'system.desc': 'Control system infrastructure, toggle maintenance mode, or publish the attributions page.',
    'system.maintenance': 'Server Maintenance Mode',
    'system.maintenance_desc': 'Enabling maintenance mode stops new login requests. Logged-in users can continue in local mode.',
    'system.checking': 'Checking Status...',
    'system.loading_btn': 'Loading...',
    'system.live': 'Live',
    'system.maintenance_on': 'MAINTENANCE',
    'system.enable_maint': 'Enable Maintenance',
    'system.disable_maint': 'Disable Maintenance',
    'system.saving': 'SAVING',
    'system.retry': 'Retry',
    'system.maint_updated': 'Maintenance mode updated successfully.',
    'system.attributions': 'Publish Attributions Page',
    'system.attributions_desc': 'Use this trigger to rebuild and publish the attributions page after model or license updates.',
    'system.attributions_synced': 'Status: Synced',
    'system.attributions_pending': 'Status: Update Required',
    'system.attributions_btn': 'Update Attributions',
    'system.attributions_publish': 'Publish Changes',
    'system.attributions_uptodate': 'Up to Date',
    'system.attributions_trigger': 'TRIGGERING...',
    'system.attributions_retry': 'Retry Publish',
    'system.export': 'Export / Download Data',
    'system.export_desc': 'Download contributor lists, AI models, or news articles in your chosen format.',
    'system.export_type': 'Data to Export',
    'system.export_contributors': 'Contributor Applications',
    'system.export_manual_models': 'Curated AI Models',
    'system.export_all_models': 'All Models Database',
    'system.export_articles': 'Published Articles',
    'system.export_format': 'File Format',
    'system.export_json': 'JSON Format (.json)',
    'system.export_csv': 'CSV Format (Excel compatible .csv)',
    'system.export_btn': 'Compile & Download',
    'system.export_no_data': 'Selected data has not been loaded yet. Please visit the relevant tab first and wait for data to load.',
    'system.export_no_rows': 'No rows to export.',
    'system.export_success': 'Data exported successfully.',
    'system.export_downloaded': 'File downloaded successfully!',
    'system.gcs_backup': 'Google Cloud Storage (GCS) Backup',
    'system.gcs_desc': 'Automated GCS organization backup mechanism (via GitHub Actions) is currently <strong style="color: var(--accent-sage);">ACTIVE</strong> and operational.',
    'system.verify_user': 'Verify Contributor (Manual)',
    'system.verify_desc': 'Instantly verify a user\'s email address by providing their Email or UID.',
    'system.verify_id': 'User UID or Email',
    'system.verify_btn': 'Verify Email',
    'system.verify_success': 'User email successfully verified.',
    'system.remove_admin': 'Revoke Admin Access',
    'system.remove_admin_desc': 'Revoke an administrator\'s privileges using their email address.',
    'system.remove_email': 'Email Address',
    'system.remove_btn': 'Revoke Access',
    'system.remove_success': 'Admin access successfully revoked.',
    'system.admin_list': 'Active System Administrators',
    'system.loading_admins': 'Loading...',
    'system.error': 'Error',
    'auth.not_admin': 'You are not authorized to access this panel.',
    'auth.login_failed': 'Login Failed:',
    'auth.enter_credentials': 'Please enter both email and password.',
    'auth.session_expired': 'Authentication session expired. Please log in again.',
    'auth.try_again': 'Try Again',
    'template.group.system': 'System & Offers',
    'template.group.engagement': 'User Engagement',
    'template.group.fun': 'Fun & Jokes',
    'template.group.tech': 'Technical Details',
    'template.group.special': 'Special Days',
    'template.newModel': 'New Model Added',
    'template.newFeature': 'New Feature Added',
    'template.upsellFeature': 'Subscription Campaign',
    'template.appUpdate': 'App Update Notice',
    'template.rateApp': 'Rate the App',
    'template.referral': 'Refer a Friend',
    'template.socialMedia': 'Social Media Engagement',
    'template.comeback': 'Comeback Call (General)',
    'template.longTimeNoSee': 'Long Time No See',
    'template.howAreYou': 'Check In',
    'template.goodMorning': 'Good Morning Message',
    'template.goodNight': 'Good Night Message',
    'template.randomFact': 'Random Fact',
    'template.showerThought': 'Shower Thoughts',
    'template.fortuneCookie': 'Fortune Cookie',
    'template.hackerJoke': 'Developer Jokes',
    'template.pirate': 'Pirate Mode',
    'template.trollAnime': 'Troll (Anime)',
    'template.trollAiRebellion': 'Troll (AI Rebellion)',
    'template.singularity': 'Singularity',
    'template.detectiveCase': 'Detective Story',
    'template.originStory': 'Story Origin',
    'template.rejectionStory': 'Rejection Memory',
    'template.cooking': 'Chef\'s Recipe',
    'template.existential': 'Existential Crisis',
    'template.openSource': 'Open Source Love',
    'template.offlineReady': 'Offline Mode Ready',
    'template.customModel': 'Bring Your Own Model',
    'template.dynamicChat': 'Dynamic Chat Rooms',
    'template.ggufSupport': 'GGUF Support Active',
    'template.themeCustomization': 'Theme Customization',
    'template.homeworkHelper': 'Homework Assistant Intro',
    'template.lowBattery': 'Low Battery Saver Mode',
    'template.newYear': 'New Year Greeting',
    'template.valentinesDay': 'Valentine\'s Day',
    'template.ataturkRemembrance': 'Nov 10 Ataturk Remembrance',
    'template.mothersDay': 'Mother\'s Day',
    'template.fathersDay': 'Father\'s Day',
  }
};

let currentLang = localStorage.getItem('siteLang') || 'tr';

export function __(key) {
  return LANG[currentLang]?.[key] || LANG['tr']?.[key] || key;
}

// Make __ available globally for inline scripts
window.__ = __;

export function getLang() {
  return currentLang;
}

export function setLang(lang) {
  if (LANG[lang]) {
    currentLang = lang;
    localStorage.setItem('siteLang', lang);
    document.documentElement.lang = lang;
    translatePage();
    dispatchLangChange();
  }
}

const langChangeCallbacks = [];

export function onLangChange(callback) {
  langChangeCallbacks.push(callback);
}

function dispatchLangChange() {
  langChangeCallbacks.forEach(cb => {
    try { cb(currentLang); } catch (e) { console.error(e); }
  });
}

export function translatePage() {
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.getAttribute('data-i18n');
    const translation = __(key);
    if (translation.includes('<')) {
      el.innerHTML = translation;
    } else {
      el.textContent = translation;
    }
  });
  document.querySelectorAll('[data-i18n-placeholder]').forEach(el => {
    const key = el.getAttribute('data-i18n-placeholder');
    el.placeholder = __(key);
  });
  document.querySelectorAll('[data-i18n-title]').forEach(el => {
    const key = el.getAttribute('data-i18n-title');
    el.title = __(key);
  });
  document.querySelectorAll('[data-i18n-value]').forEach(el => {
    const key = el.getAttribute('data-i18n-value');
    el.value = __(key);
  });
  // Update page title
  const titleKey = document.querySelector('title')?.getAttribute('data-i18n');
  if (titleKey) document.title = __(titleKey);
  const metaDesc = document.querySelector('meta[name="description"]');
  if (metaDesc?.getAttribute('data-i18n')) {
    metaDesc.content = __(metaDesc.getAttribute('data-i18n'));
  }
  // Update select option text content
  document.querySelectorAll('select[data-i18n-options]').forEach(select => {
    Array.from(select.options).forEach(opt => {
      const key = opt.getAttribute('data-i18n');
      if (key) opt.textContent = __(key);
    });
  });
}
